/**
 * Red-green + guard tests for the Gemini Live probe's REQUESTED RESPONSE MODALITY.
 *
 * THE BUG. The probe opened every Live session with
 * `generationConfig.responseModalities = ["TEXT"]`. Every model exposing
 * `bidiGenerateContent` is a native-audio model that supports only `AUDIO`
 * (Google's capabilities guide: the native audio models "only support `AUDIO`
 * response modality"), so the provider REFUSED the session out-of-band with an
 * RFC 6455 CLOSE frame, recovered verbatim from a live drift run:
 *
 *   code=1007 reason="The requested combination of response modalities (TEXT) is
 *   not supported by the model. models/gemini-3.1-flash-live-preview"
 *
 * 1007 is a refusal, not a timeout — the request never had a chance of being
 * served, so the leg reported provider-refusal noise instead of drift on every
 * run.
 *
 * THE PROOF. These tests stand up a local TLS server that ENFORCES Google's
 * rule — one modality per session, `AUDIO` only — and drive the REAL exported
 * `geminiLiveWS` probe against it through the REAL `connectTLSWebSocket`
 * transport and the REAL server-side `WebSocketConnection` framing. Nothing
 * about the protocol path is reimplemented here, so:
 *
 *   RED   — with the probe requesting `["TEXT"]`, "drives a complete AUDIO turn"
 *           fails with exactly the 1007 frame above.
 *   GREEN — with the probe requesting `["AUDIO"]`, it observes a real audio
 *           event sequence: setupComplete → inlineData parts → turnComplete.
 *
 * The refusal itself is anchored to `OBSERVED_1007_REASON`, copied from the
 * drift-report artifact rather than generated by this file's expectations.
 *
 * NOT PROVEN HERE: that the live endpoint accepts `["AUDIO"]` and emits this
 * exact sequence. That is established from Google's published capabilities guide
 * and can only be confirmed by a live run with a real GOOGLE_API_KEY.
 */
import { describe, it, expect, beforeAll, afterAll } from "vitest";
import * as tls from "node:tls";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { execFileSync } from "node:child_process";
import { computeAcceptKey, WebSocketConnection } from "../../ws-framing.js";
import type { ServerInstance } from "../../server.js";
import {
  connectTLSWebSocket,
  geminiLiveWS,
  summarizeGeminiLiveTurn,
  classifyGeminiMessage,
  GEMINI_LIVE_RESPONSE_MODALITIES,
  WSClosedError,
} from "./ws-providers.js";
import { extractShape, compareSSESequences } from "./schema.js";
import { geminiLiveSetupCompleteShape, geminiLiveAudioEventShapes } from "./sdk-shapes.js";
import {
  startDriftServer,
  stopDriftServer,
  collectMockWSMessages,
  GEMINI_WS_PATH,
  AUDIO_PROMPT,
} from "./helpers.js";
import { connectWebSocket } from "../ws-test-client.js";

// ---------------------------------------------------------------------------
// The observed live failure, verbatim
// ---------------------------------------------------------------------------

/** The model the live listing resolved to when the refusal was observed. */
const OBSERVED_MODEL = "models/gemini-3.1-flash-live-preview";

/**
 * The CLOSE reason Google sent, copied verbatim from the `drift-report-base`
 * artifact of the failing run. Anchoring the reproduction to the recorded bytes
 * keeps this test honest: it reproduces what the provider actually said rather
 * than what this file finds convenient to assert.
 */
const OBSERVED_1007_REASON =
  "The requested combination of response modalities (TEXT) is not supported by the model. " +
  OBSERVED_MODEL;

// ---------------------------------------------------------------------------
// A local TLS server that enforces Google's modality rule
// ---------------------------------------------------------------------------

let certDir: string;
let key: Buffer;
let cert: Buffer;

beforeAll(() => {
  certDir = fs.mkdtempSync(path.join(os.tmpdir(), "aimock-gemini-modality-"));
  const keyPath = path.join(certDir, "key.pem");
  const certPath = path.join(certDir, "cert.pem");
  // A throwaway self-signed cert, generated per-run so no private key is ever
  // committed. Node requires a subjectAltName (a CN alone is rejected).
  execFileSync(
    "openssl",
    [
      "req",
      "-x509",
      "-newkey",
      "rsa:2048",
      "-nodes",
      "-keyout",
      keyPath,
      "-out",
      certPath,
      "-days",
      "1",
      "-subj",
      "/CN=localhost",
      "-addext",
      "subjectAltName=DNS:localhost,IP:127.0.0.1",
    ],
    { stdio: "ignore" },
  );
  key = fs.readFileSync(keyPath);
  cert = fs.readFileSync(certPath);
});

afterAll(() => {
  if (certDir) fs.rmSync(certDir, { recursive: true, force: true });
});

/** Knobs that let a guard test break exactly one part of the expected turn. */
interface FakeProviderOptions {
  /** Answer with `text` parts instead of `inlineData` audio parts. */
  emitTextInsteadOfAudio?: boolean;
  /** Never end the turn. */
  omitTurnComplete?: boolean;
  /** Accept the socket and say NOTHING — not even `setupComplete`. */
  muteFromStart?: boolean;
  /** Send `setupComplete`, then ignore the client's turn entirely. */
  muteAfterSetup?: boolean;
}

/** The client-to-server messages the fake provider understands. */
interface LiveClientMessage {
  setup?: {
    model?: string;
    tools?: unknown[];
    generationConfig?: { responseModalities?: unknown };
  };
  clientContent?: unknown;
}

/** The server-to-client fields these tests read back off the wire. */
interface LiveServerMessage {
  setupComplete?: unknown;
  toolCall?: unknown;
  serverContent?: { turnComplete?: boolean };
}

/** The probe's terminal predicate: the turn ended, or the model called a tool. */
function isTurnTerminal(msg: unknown): boolean {
  const m = msg as LiveServerMessage | null;
  return m?.serverContent?.turnComplete === true || (!!m && "toolCall" in m);
}

interface FakeProvider {
  port: number;
  /** Every message the "provider" received, parsed. */
  received: LiveClientMessage[];
  stop: () => void;
}

/**
 * Stand up a fake Gemini Live endpoint.
 *
 * It enforces the rule the real provider enforces — a Live session carries
 * EXACTLY ONE response modality and it must be `AUDIO` — and refuses anything
 * else with the same 1007 frame shape Google sent. The rule lives here, in the
 * "provider", NOT in the expectations: a probe that asks for the wrong modality
 * is rejected by the server, so the red/green below cannot be satisfied by
 * agreeing with itself.
 */
function startFakeProvider(options: FakeProviderOptions = {}): Promise<FakeProvider> {
  return new Promise((resolve) => {
    const received: LiveClientMessage[] = [];
    const sockets: tls.TLSSocket[] = [];

    const server = tls.createServer({ key, cert }, (socket) => {
      sockets.push(socket);
      socket.on("error", () => {
        /* the client tears sockets down mid-flight; not a test failure */
      });

      socket.once("data", (handshake: Buffer) => {
        const wsKey = /sec-websocket-key:\s*(\S+)/i.exec(handshake.toString())?.[1] ?? "";
        socket.write(
          "HTTP/1.1 101 Switching Protocols\r\n" +
            "Upgrade: websocket\r\n" +
            "Connection: Upgrade\r\n" +
            `Sec-WebSocket-Accept: ${computeAcceptKey(wsKey)}\r\n\r\n`,
        );

        // The repo's own server-side framing — unmasks client frames and frames
        // ours — so no WebSocket codec is hand-rolled in this test.
        const conn = new WebSocketConnection(socket);
        let hasTools = false;

        conn.on("message", (raw: string) => {
          // The live failure mode: the session is accepted and nothing comes
          // back. Handled before parsing so the provider is mute no matter what
          // the probe sends.
          if (options.muteFromStart) return;
          let msg: LiveClientMessage;
          try {
            msg = JSON.parse(raw) as LiveClientMessage;
          } catch {
            conn.close(1007, "Malformed JSON");
            return;
          }
          received.push(msg);

          const setup = msg.setup;
          if (setup) {
            const model: string = setup.model ?? OBSERVED_MODEL;
            const modalities = setup.generationConfig?.responseModalities;
            // Google's rule: exactly one modality, and AUDIO is the only one a
            // native-audio Live model serves.
            const ok =
              Array.isArray(modalities) && modalities.length === 1 && modalities[0] === "AUDIO";
            if (!ok) {
              const requested = Array.isArray(modalities)
                ? modalities.join(", ")
                : String(modalities);
              conn.close(
                1007,
                `The requested combination of response modalities (${requested}) is not ` +
                  `supported by the model. ${model}`,
              );
              return;
            }
            hasTools = Array.isArray(setup.tools) && setup.tools.length > 0;
            conn.send(JSON.stringify({ setupComplete: {} }));
            return;
          }

          if (msg.clientContent) {
            // A session that establishes fine and then produces no turn — the
            // OTHER cause a zero-message live failure can have.
            if (options.muteAfterSetup) return;
            if (hasTools) {
              conn.send(
                JSON.stringify({
                  toolCall: {
                    functionCalls: [
                      { name: "get_weather", args: { city: "Paris" }, id: "function-call-1" },
                    ],
                  },
                }),
              );
            } else if (options.emitTextInsteadOfAudio) {
              conn.send(
                JSON.stringify({
                  serverContent: { modelTurn: { parts: [{ text: "Hello!" }] } },
                }),
              );
            } else {
              // Two audio frames, as a real audio turn streams.
              for (const data of ["AAAAAA==", "BBBBBB=="]) {
                conn.send(
                  JSON.stringify({
                    serverContent: {
                      modelTurn: {
                        parts: [{ inlineData: { mimeType: "audio/pcm;rate=24000", data } }],
                      },
                    },
                  }),
                );
              }
              conn.send(JSON.stringify({ serverContent: { generationComplete: true } }));
            }
            if (!options.omitTurnComplete) {
              conn.send(JSON.stringify({ serverContent: { turnComplete: true } }));
            }
          }
        });
      });
    });

    server.listen(0, "127.0.0.1", () => {
      const port = (server.address() as { port: number }).port;
      resolve({
        port,
        received,
        stop: () => {
          for (const s of sockets) s.destroy();
          server.close();
        },
      });
    });
  });
}

/** Run `body` against a fresh fake provider, guaranteeing teardown. */
async function withProvider<T>(
  options: FakeProviderOptions,
  body: (provider: FakeProvider) => Promise<T>,
): Promise<T> {
  const provider = await startFakeProvider(options);
  try {
    return await body(provider);
  } finally {
    provider.stop();
  }
}

/** Drive the REAL probe against the fake provider. */
function probe(provider: FakeProvider, tools?: object[], waitMs?: number) {
  return geminiLiveWS({ apiKey: "fake-key" }, "Greet me aloud", tools, OBSERVED_MODEL, {
    host: "localhost",
    port: provider.port,
    ca: cert,
    waitMs,
  });
}

// ---------------------------------------------------------------------------
// The reproduction: what the live endpoint did to a TEXT request
// ---------------------------------------------------------------------------

describe("REPRODUCTION: a TEXT-modality Live session is refused with 1007", () => {
  it("reproduces the observed close frame for the pre-fix setup body", async () => {
    // The setup body the probe used to send, verbatim.
    const err = await withProvider({}, async (provider) => {
      const ws = await connectTLSWebSocket("localhost", "/probe", undefined, {
        port: provider.port,
        ca: cert,
      });
      ws.send(
        JSON.stringify({
          setup: {
            model: OBSERVED_MODEL,
            generationConfig: { responseModalities: ["TEXT"] },
          },
        }),
      );
      return await ws
        .waitUntil((m: unknown) => !!m && typeof m === "object" && "setupComplete" in m, 3000)
        .then(
          () => null,
          (e: unknown) => e,
        );
    });

    expect(err).toBeInstanceOf(WSClosedError);
    const closed = err as WSClosedError;
    expect(closed.code).toBe(1007);
    // Byte-identical to the reason recorded in the live drift-report artifact.
    expect(closed.reason).toBe(OBSERVED_1007_REASON);
  });

  it("refuses a TEXT+AUDIO combination too — a Live session carries exactly one modality", async () => {
    const err = await withProvider({}, async (provider) => {
      const ws = await connectTLSWebSocket("localhost", "/probe", undefined, {
        port: provider.port,
        ca: cert,
      });
      ws.send(
        JSON.stringify({
          setup: {
            model: OBSERVED_MODEL,
            generationConfig: { responseModalities: ["TEXT", "AUDIO"] },
          },
        }),
      );
      return await ws
        .waitUntil((m: unknown) => !!m && typeof m === "object" && "setupComplete" in m, 3000)
        .then(
          () => null,
          (e: unknown) => e,
        );
    });

    expect(err).toBeInstanceOf(WSClosedError);
    expect((err as WSClosedError).code).toBe(1007);
    expect((err as WSClosedError).reason).toContain("(TEXT, AUDIO)");
  });
});

// ---------------------------------------------------------------------------
// The CURRENT live failure: accepted, then nothing
// ---------------------------------------------------------------------------
//
// The live legs now fail as a bare zero-message timeout. Two causes produce
// that, and the drift-report artifact could not tell them apart:
//
//   A. the session was never established — no `setupComplete` ever arrived;
//   B. the session WAS established and the turn produced nothing.
//
// The per-call message cursor means B's collected count is also 0 (step 2
// consumed the `setupComplete`), so both printed `Collected 0 messages: []`.
// These two tests are the discriminator, driven through the REAL probe: the
// failure now names the step it was on AND the dynamically-resolved model, so
// the next live run states which cause it hit instead of repeating the
// ambiguity.

describe("a zero-message live failure names its cause", () => {
  it("A: a provider mute from the start fails at step=setupComplete", async () => {
    const err = (await withProvider({ muteFromStart: true }, (provider) =>
      probe(provider, undefined, 500).then(
        () => null,
        (e: unknown) => e,
      ),
    )) as Error;

    expect(err).toBeInstanceOf(Error);
    expect(err.message).toContain("step=setupComplete");
    expect(err.message).toContain(`model=${OBSERVED_MODEL}`);
    // Nothing was read because nothing was sent — an all-zero data tally is the
    // transport stating it was not the deaf party.
    expect(err.message).toContain("frames text=0 binary=0");
  });

  it("B: a provider that answers setup but not the turn fails at step=turn", async () => {
    const err = (await withProvider({ muteAfterSetup: true }, (provider) =>
      probe(provider, undefined, 500).then(
        () => null,
        (e: unknown) => e,
      ),
    )) as Error;

    expect(err).toBeInstanceOf(Error);
    // The distinction the artifact could not previously make.
    expect(err.message).toContain("step=turn");
    expect(err.message).toContain(`model=${OBSERVED_MODEL}`);
    // The session WAS established: one frame was read before the surface went
    // quiet, which is what separates this from case A.
    expect(err.message).toContain("frames text=1");
  });
});

// ---------------------------------------------------------------------------
// GREEN: the probe drives a complete AUDIO turn
// ---------------------------------------------------------------------------

describe("the Gemini Live probe requests a modality the model serves", () => {
  it("requests exactly [AUDIO] in generationConfig.responseModalities", async () => {
    // Asserted against the literal the provider accepts, NOT against the
    // probe's own exported constant — otherwise changing the constant would
    // move this expectation with it and prove nothing.
    const received = await withProvider({}, async (provider) => {
      await probe(provider);
      return provider.received;
    });

    const setup = received.find((m) => m.setup)?.setup;
    expect(setup, "the probe sent no setup message at all").toBeDefined();
    // Optional chaining, so a probe that dropped generationConfig entirely
    // yields `undefined` here and still fails this assertion rather than
    // throwing before it is reached.
    expect(setup?.generationConfig?.responseModalities).toEqual(["AUDIO"]);
  });

  it("drives a complete AUDIO turn: setupComplete, inlineData parts, turnComplete", async () => {
    const result = await withProvider({}, (provider) => probe(provider));

    const turn = summarizeGeminiLiveTurn(result.rawMessages);
    expect(turn.setupCompleteCount).toBe(1);
    expect(turn.audioPartCount).toBe(2);
    expect(turn.turnCompleteCount).toBe(1);
    // AUDIO modality means no text parts on the wire.
    expect(turn.textPartCount).toBe(0);

    // The classified event sequence the drift comparison grades on.
    expect(result.events.map((e) => e.type)).toEqual([
      "setupComplete",
      "serverContent",
      "serverContent",
      "serverContent",
      "serverContent",
    ]);
  });

  it("still observes a toolCall when the session declares functionDeclarations", async () => {
    const tools = [
      {
        functionDeclarations: [
          {
            name: "get_weather",
            description: "Get weather",
            parameters: { type: "object", properties: { city: { type: "string" } } },
          },
        ],
      },
    ];
    const result = await withProvider({}, (provider) => probe(provider, tools));

    const turn = summarizeGeminiLiveTurn(result.rawMessages);
    expect(turn.setupCompleteCount).toBe(1);
    expect(turn.toolCallCount).toBe(1);
  });
});

// ---------------------------------------------------------------------------
// GUARDS: the observation must be able to fail
// ---------------------------------------------------------------------------

describe("GUARD: the AUDIO-turn observation distinguishes a real turn from a broken one", () => {
  it("counts ZERO audio parts when the provider answers with text parts", async () => {
    // The drift leg asserts audioPartCount > 0. If this returned a nonzero count
    // for a text answer, that assertion could never notice the provider dropping
    // audio — the leg would report silence as health.
    const result = await withProvider({ emitTextInsteadOfAudio: true }, (provider) =>
      probe(provider),
    );

    const turn = summarizeGeminiLiveTurn(result.rawMessages);
    expect(turn.audioPartCount).toBe(0);
    expect(turn.textPartCount).toBe(1);
  });

  it("counts ZERO completions when the provider never ends the turn", async () => {
    // The provider streams audio and stops. The probe's terminal predicate is
    // never satisfied, so it must NOT return a turn it can call complete.
    const result = await withProvider({ omitTurnComplete: true }, async (provider) => {
      const ws = await connectTLSWebSocket("localhost", "/probe", undefined, {
        port: provider.port,
        ca: cert,
      });
      ws.send(
        JSON.stringify({
          setup: {
            model: OBSERVED_MODEL,
            generationConfig: { responseModalities: ["AUDIO"] },
          },
        }),
      );
      await ws.waitUntil(
        (m: unknown) => !!m && typeof m === "object" && "setupComplete" in m,
        3000,
      );
      ws.send(JSON.stringify({ clientContent: { turns: [], turnComplete: true } }));
      const err = await ws.waitUntil(isTurnTerminal, 1500).then(
        () => null,
        (e: unknown) => e,
      );
      ws.close();
      return err;
    });

    // A turn that never completes surfaces as a timeout, not as a pass.
    expect(result).toBeInstanceOf(Error);
    expect((result as Error).message).toContain("waitUntil timeout");
  });

  it("counts ZERO audio parts and ZERO completions for an empty message list", async () => {
    // Cheap sanity floor: the summary cannot manufacture observations.
    expect(summarizeGeminiLiveTurn([])).toEqual({
      setupCompleteCount: 0,
      audioPartCount: 0,
      textPartCount: 0,
      turnCompleteCount: 0,
      toolCallCount: 0,
    });
  });

  it("ignores non-object junk on the wire rather than counting it", async () => {
    expect(summarizeGeminiLiveTurn([null, undefined, "oops", 42])).toEqual({
      setupCompleteCount: 0,
      audioPartCount: 0,
      textPartCount: 0,
      turnCompleteCount: 0,
      toolCallCount: 0,
    });
  });
});

// ---------------------------------------------------------------------------
// The three-way comparison, run locally end to end
// ---------------------------------------------------------------------------
//
// The live drift leg's own three-way grading only executes with a real
// GOOGLE_API_KEY. This runs the SAME grading — the same sdk shapes, the same
// `compareSSESequences`, the same aimock WS handler over the same drift-server
// fixtures — with the fake provider standing in for Google, so the MOCK side of
// the leg is verified here instead of first being exercised in CI against a live
// endpoint. It proves aimock reproduces the AUDIO turn's shape; it does NOT
// prove Google emits that shape (only a live run can).

describe("three-way AUDIO comparison: sdk shapes × provider turn × aimock", () => {
  let instance: ServerInstance;

  beforeAll(async () => {
    instance = await startDriftServer();
  });

  afterAll(async () => {
    await stopDriftServer(instance);
  });

  /** Drive aimock exactly as the drift leg's mock side does. */
  async function driveMock(): Promise<unknown[]> {
    const mockWs = await connectWebSocket(instance.url, GEMINI_WS_PATH);
    mockWs.send(
      JSON.stringify({
        setup: {
          model: OBSERVED_MODEL,
          generationConfig: { responseModalities: GEMINI_LIVE_RESPONSE_MODALITIES },
        },
      }),
    );
    const setupMsgs = await mockWs.waitForMessages(1);
    const raw: unknown[] = [JSON.parse(setupMsgs[0])];
    mockWs.send(
      JSON.stringify({
        clientContent: {
          turns: [{ role: "user", parts: [{ text: AUDIO_PROMPT }] }],
          turnComplete: true,
        },
      }),
    );
    const content = await collectMockWSMessages(
      mockWs,
      (msg) => (msg as LiveServerMessage | null)?.serverContent?.turnComplete === true,
      15000,
      1,
    );
    raw.push(...content.rawMessages);
    mockWs.close();
    return raw;
  }

  it("aimock streams an AUDIO turn for the drift server's audio fixture", async () => {
    const turn = summarizeGeminiLiveTurn(await driveMock());
    expect(turn.setupCompleteCount).toBe(1);
    expect(turn.audioPartCount).toBeGreaterThan(0);
    expect(turn.turnCompleteCount).toBeGreaterThan(0);
    expect(turn.textPartCount).toBe(0);
  });

  it("reports NO critical drift between the sdk audio shape, the provider turn, and aimock", async () => {
    const realResult = await withProvider({}, (provider) => probe(provider));
    const mockRaw = await driveMock();
    const mockEvents = mockRaw.map((msg) => ({
      type: classifyGeminiMessage(msg as Record<string, unknown>),
      dataShape: extractShape(msg),
    }));

    const diffs = compareSSESequences(
      [geminiLiveSetupCompleteShape(), ...geminiLiveAudioEventShapes()],
      realResult.events,
      mockEvents,
    );

    expect(diffs.filter((d) => d.severity === "critical")).toEqual([]);
  });

  it("GUARD: a mock missing the audio payload IS reported as critical drift", async () => {
    // Non-vacuity of the test above. If the mock's serverContent lost its
    // inlineData, the comparison must go critical — otherwise "no critical
    // drift" means nothing. The mock side here is a text turn (aimock's TEXT
    // shape) graded against the provider's AUDIO turn.
    const realResult = await withProvider({}, (provider) => probe(provider));
    const textShapedMock = [
      { type: "setupComplete", dataShape: extractShape({ setupComplete: {} }) },
      {
        type: "serverContent",
        dataShape: extractShape({
          serverContent: { modelTurn: { parts: [{ text: "Hello!" }] }, turnComplete: true },
        }),
      },
    ];

    const diffs = compareSSESequences(
      [geminiLiveSetupCompleteShape(), ...geminiLiveAudioEventShapes()],
      realResult.events,
      textShapedMock,
    );

    const critical = diffs.filter((d) => d.severity === "critical");
    expect(critical.length).toBeGreaterThan(0);
    expect(critical.map((d) => d.path).join(" ")).toContain("inlineData");
  });
});
